#include "ScriptMgr.h"
#include "Player.h"
#include "Map.h"
#include "Config.h"
#include "Log.h"
#include "LiveMapMgr.h"
#include "GuildMgr.h"
#include <unordered_map>
#include <mutex>
static std::unordered_map<uint32,uint32> _lastPlayerUpdate,_lastBotUpdate; static std::mutex _lastUpdateMutex;
static bool IsBotPlayer(Player* p){ if(!p) return false; if(!p->GetSession()) return true; if(p->GetSession()->GetRemoteAddress().empty()) return true; return false; }
static std::string GetBehaviorState(Player* player,bool isDead,bool inCombat,bool isInFlight){ if(isDead) return "Dead"; if(isInFlight) return "Flight"; if(inCombat) return "Combat"; if(!player) return "Unknown"; if(player->HasUnitState(UNIT_STATE_LOOTING)) return "Looting"; if(player->IsFalling()) return "Falling"; if(player->isMoving()) return "Traveling"; if(player->HasFlag(PLAYER_FLAGS,PLAYER_FLAGS_RESTING)) return "Resting"; return player->GetSession()&&!player->GetSession()->GetRemoteAddress().empty()?"Idle":"Grinding"; }
class LiveMap_PlayerScript:public PlayerScript{public:LiveMap_PlayerScript():PlayerScript("LiveMap_PlayerScript"){} void OnPlayerUpdate(Player* player,uint32)override{ if(!sConfigMgr->GetOption<bool>("LiveMap.Enable",true)) return; if(!player||!player->IsInWorld()||player->IsBeingTeleported()) return; uint32 mapId=player->GetMapId(); if(!sLiveMap->IsMapTracked(mapId)) return; bool isBot=IsBotPlayer(player); if(player->IsGameMaster()&&!isBot){ if(!sConfigMgr->GetOption<bool>("LiveMap.TrackGM",false)) return; if(!player->isGMVisible()&&!sConfigMgr->GetOption<bool>("LiveMap.TrackGMInvisible",false)) return; } uint32 guidLow=player->GetGUID().GetCounter(); uint32 now=getMSTime(); uint32 pInt=sConfigMgr->GetOption<uint32>("LiveMap.UpdateIntervalMs",1000); uint32 bInt=sConfigMgr->GetOption<uint32>("LiveMap.BotUpdateIntervalMs",3000); uint32 interval=isBot?bInt:pInt; { std::lock_guard<std::mutex> g(_lastUpdateMutex); auto& m=isBot?_lastBotUpdate:_lastPlayerUpdate; auto it=m.find(guidLow); if(it!=m.end()&&(now-it->second)<interval) return; m[guidLow]=now; } std::string guildName=""; if(Guild* g=sGuildMgr->GetGuildById(player->GetGuildId())) guildName=g->GetName(); bool isDead=!player->IsAlive(); bool inCombat=player->IsInCombat(); bool isInFlight=player->IsInFlight(); uint32 taxiOrigin=0,taxiDest=0; if(isInFlight){ if(player->m_taxi.GetTaxiSource()) taxiOrigin=player->m_taxi.GetTaxiSource(); if(player->m_taxi.GetTaxiDestination()) taxiDest=player->m_taxi.GetTaxiDestination(); } std::string behavior=GetBehaviorState(player,isDead,inCombat,isInFlight); uint32 totalPlayed=player->GetTotalPlayedTime(); uint32 levelPlayed=player->GetLevelPlayedTime(); uint32 money=player->GetMoney(); float healthPct=player->GetMaxHealth()>0?(float)player->GetHealth()*100.0f/(float)player->GetMaxHealth():0; float manaPct=player->GetMaxPower(POWER_MANA)>0?(float)player->GetPower(POWER_MANA)*100.0f/(float)player->GetMaxPower(POWER_MANA):0; uint32 latency=player->GetSession()?player->GetSession()->GetLatency():0; sLiveMap->QueueUpdate(guidLow,player->GetName(),mapId,player->GetPositionX(),player->GetPositionY(),player->GetPositionZ(),player->GetZoneId(),player->getLevel(),player->getClass(),isBot,player->GetTeamId(),player->getRace(),guildName,isDead,inCombat,behavior,isInFlight,taxiOrigin,taxiDest,totalPlayed,levelPlayed,money,healthPct,manaPct,latency); } void OnPlayerLogout(Player* p)override{ if(!p) return; uint32 id=p->GetGUID().GetCounter(); { std::lock_guard<std::mutex> g(_lastUpdateMutex); _lastPlayerUpdate.erase(id); _lastBotUpdate.erase(id);} sLiveMap->RemovePlayer(id); } void OnPlayerLogin(Player* p)override{ if(!p) return; uint32 id=p->GetGUID().GetCounter(); std::lock_guard<std::mutex> g(_lastUpdateMutex); _lastPlayerUpdate.erase(id); _lastBotUpdate.erase(id); } };
class LiveMap_WorldScript:public WorldScript{public:LiveMap_WorldScript():WorldScript("LiveMap_WorldScript"){} void OnStartup()override{ sLiveMap->Init(); LOG_INFO("module","[LiveMap] Started secure v2 +deadlock fix"); } void OnShutdown()override{ sLiveMap->Shutdown(); } void OnAfterUpdate(uint32 diff)override{ static uint32 t=0; t+=diff; if(t>=500){ sLiveMap->Flush(); t=0; } } };
void Addmod_live_mapScripts(){ new LiveMap_PlayerScript(); new LiveMap_WorldScript(); }
